version: '3'

services:
  app:
    image: 'boostify:latest'
    build:
      context: ../Boostify
    container_name: boostify-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://boostify-postgres:5432/boostify-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8080:8080'
    expose:
      - '8080'

  db:
    image: 'postgres:13.1-alpine'
    container_name: boostify-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boostify-db
    ports:
      - '5432:5432'
    expose:
      - '5432'